### ISSUE TITLE
multivariate localC perm incorrect

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/spdep#74] opened 2022-01-11 14:16 UTC
When calling `sample.int()`, the length of `x` is used which is `nrow(x) * ncol(x)` in the multivariate context since it is cast a matrix. Reproducible code for this problem is below .

It appears that the error stems from `localC_perm_calc()` though I am still unclear what the function is doing—mainly the `permC_int()` subroutine. I've spent ~an hour trying to debug this but am struggling. The problem seems to extend past the sampling. 

If you have suggestions where to look, I'll give it a shot! Thanks.

```
library(sf)
library(spdep)

g <- Guerry::gfrance85
nb <- spdep::poly2nb(g)
listw <- nb2listw(nb)
x <- list(g$Crime_pers, g$Crime_prop)

localC_perm(x, listw)
localC(x, listw)
```

https://github.com/r-spatial/spdep/blob/b3a613f621e88d5930d00ffce56c1287be4c5633/R/localC.R#L239

**Comment by rsbivand** [comment] 2022-01-11 16:33
The problem in conditional=FALSE is that the output pseudo-p object should have been an array if the input was multivariable, so we get a 85*499 row matrix  with 8 columns. With conditional=TRUE, we get a 85*8 by 2 matrix, also wrong. The univariate local C_i are OK, rgeoda's inivariate p-values are broken https://github.com/GeoDaCenter/rgeoda/issues/28. In any case, sampling should be conditional, so I'll try to see how to do the simulations on an i-vector of values, not assuming univariate (which I had done, sorry).

**Comment by rsbivand** [comment] 2022-01-12 09:00
I'm starting a `multi_localC` branch, and starting on reproducing as much of Anselin (2019) as possible. So for now please wait with PRs to `main`; I'll report here when the branch is pushed to github.

**Comment by rsbivand** [comment] 2022-01-12 15:31
For now please compare these univariate results with the GA article:
```
library(sf)
library(spdep)
run <- FALSE
if (require(rgeoda, quietly=TRUE)) run <- TRUE
tmap_ok <- FALSE
if (require(tmap, quietly=TRUE)) tmap_ok <- TRUE
if (run) {
  # doi: 10.1111/gean.12164
  guerry_path <- system.file("extdata", "Guerry.shp", package = "rgeoda")
  g <- st_read(guerry_path)[, 7:12]
  cor(st_drop_geometry(g)) #(Tab. 1)
  lw <- nb2listw(poly2nb(g))
  moran(g$Crm_prs, lw, n=nrow(g), S0=Szero(lw))$I
  moran(g$Crm_prp, lw, n=nrow(g), S0=Szero(lw))$I
  moran(g$Litercy, lw, n=nrow(g), S0=Szero(lw))$I
  moran(g$Donatns, lw, n=nrow(g), S0=Szero(lw))$I
  moran(g$Infants, lw, n=nrow(g), S0=Szero(lw))$I
  moran(g$Suicids, lw, n=nrow(g), S0=Szero(lw))$I
}
if (run) {
  o <- prcomp(st_drop_geometry(g), scale.=TRUE)
  cor(st_drop_geometry(g), o$x[,1:2])^2 #(Tab. 2)
}
if (run) {
  g$PC1 <- o$x[, "PC1"]
  brks <- c(min(g$PC1), natural_breaks(k=6, g["PC1"]), max(g$PC1))
  if (tmap_ok) tm_shape(g) + tm_fill("PC1", breaks=brks, midpoint=0) + 
    tm_borders() # Fig. 1
  else pplot(g["PC1"], breaks=brks)
}
if (run) {
  g$PC2 <- -1*o$x[, "PC2"] # eigenvalue sign arbitrary
  brks <- c(min(g$PC2), natural_breaks(k=6, g["PC2"]), max(g$PC2))
  if (tmap_ok) tm_shape(g) + tm_fill("PC2", breaks=brks, midpoint=0) + 
    tm_borders() # Fig. 2
  else plot(g["PC2"], breaks=brks)
}
if (run) {
  w <- queen_weights(g)
  lm_PC1 <- local_moran(w, g["PC1"], significance_cutoff=0.01,
    permutations=99999)
  g$lm_PC1 <- factor(lisa_clusters(lm_PC1), levels=0:4,
    labels=lisa_labels(lm_PC1)[1:5])
  is.na(g$lm_PC1) <- g$lm_PC1 == "Not significant"
  g$lm_PC1 <- droplevels(g$lm_PC1)
  if (tmap_ok) tm_shape(g) + tm_fill("lm_PC1", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 3
  else plot(g["lm_PC1"])
}
if (run) {
  set.seed(1)
  lm_PC1_spdep <- localmoran_perm(g$PC1, lw, nsim=99999)
  q <- attr(lm_PC1_spdep, "quadr")$pysal
  g$lm_PC1_spdep <- q
  is.na(g$lm_PC1_spdep) <- lm_PC1_spdep[,6] > 0.02 # note folded p-values
  g$lm_PC1_spdep <- droplevels(g$lm_PC1_spdep)
  if (tmap_ok) tm_shape(g) + tm_fill("lm_PC1_spdep", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # rep. Fig. 3
  else plot(g["lm_PC1_spdep"])
}
if (run) {
  lg_PC1 <- local_g(w, g["PC1"], significance_cutoff=0.01,
    permutations=99999)
  g$lg_PC1 <- factor(lisa_clusters(lg_PC1), levels=0:2,
    labels=lisa_labels(lg_PC1)[0:3])
  is.na(g$lg_PC1) <- g$lg_PC1 == "Not significant"
  g$lg_PC1 <- droplevels(g$lg_PC1)
  if (tmap_ok) tm_shape(g) + tm_fill("lg_PC1", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 4
  else plot(g["lg_PC1"])
}
if (run) {
  lc_PC1 <- local_geary(w, g["PC1"], significance_cutoff=0.01,
    permutations=99999)
  g$lc_PC1 <- factor(lisa_clusters(lc_PC1), levels=0:4,
    labels=lisa_labels(lc_PC1)[1:5])
  is.na(g$lc_PC1) <- g$lc_PC1 == "Not significant"
  g$lc_PC1 <- droplevels(g$lc_PC1)
  if (tmap_ok) tm_shape(g) + tm_fill("lc_PC1", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 5
  else plot(g["lc_PC1"])
}
if (run) {
  set.seed(1)
  lc_PC1_spdep <- localC_perm(g$PC1, lw, nsim=99999, alternative="two.sided",
    conditional=TRUE)
#  q <- attr(lc_PC1_spdep, "quadr")$pysal
#  g$lc_PC1_spdep <- q
  a <- scale(g$PC1, scale=FALSE)
  b <- lag(lw, a)
  q <- integer(nrow(g))
  for (i in seq_along(q)) {
    if (a[i] > 0 && b[i] > 0) q[i] <- 1L
    else if (a[i] <= 0 && b[i] > 0) q[i] <- 3L
    else if (a[i] <= 0 && b[i] <= 0) q[i] <- 2L
    else q[i] <- 4L
  }
  q <- factor(q, levels=1:4, labels=c("High-High", "Low-Low", "Other Positive", "Negative"))
  g$lc_PC1_spdep <- q
  is.na(g$lc_PC1_spdep) <- attr(lc_PC1_spdep, "pseudo-p")[,6] > 0.01
  g$lc_PC1_spdep <- droplevels(g$lc_PC1_spdep)
  if (tmap_ok) tm_shape(g) + tm_fill("lc_PC1_spdep", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # rep. Fig. 5
  else plot(g["lc_PC1_spdep"])
}
if (run) {
  g$both_PC1 <- interaction(g$lc_PC1, g$lm_PC1)
  g$both_PC1 <- droplevels(g$both_PC1)
  if (tmap_ok) tm_shape(g) + tm_fill("both_PC1", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 6
  else plot(g["both_PC1"])
}
if (run) {
  lc005_PC1 <- local_geary(w, g["PC1"], significance_cutoff=0.005,
    permutations=99999)
  g$lc005_PC1 <- factor(lisa_clusters(lc005_PC1), levels=0:4,
    labels=lisa_labels(lc005_PC1)[1:5])
  is.na(g$lc005_PC1) <- g$lc005_PC1 == "Not significant"
  g$lc005_PC1 <- droplevels(g$lc005_PC1)
  if (tmap_ok) tm_shape(g) + tm_fill("lc005_PC1", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 7
  else plot(g["lc005_PC1"])
}
if (run) {
  lc001_PC1 <- local_geary(w, g["PC1"], significance_cutoff=0.001,
    permutations=99999)
  g$lc001_PC1 <- factor(lisa_clusters(lc001_PC1), levels=0:4,
    labels=lisa_labels(lc001_PC1)[1:5])
  is.na(g$lc001_PC1) <- g$lc001_PC1 == "Not significant"
  g$lc001_PC1 <- droplevels(g$lc001_PC1)
  if (tmap_ok) tm_shape(g) + tm_fill("lc001_PC1", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 8
  else plot(g["lc001_PC1"])
}
if (run) {
  lc_PC2 <- local_geary(w, g["PC2"], significance_cutoff=0.01,
    permutations=99999)
  g$lc_PC2 <- factor(lisa_clusters(lc_PC2), levels=0:4,
    labels=lisa_labels(lc_PC2)[1:5])
  is.na(g$lc_PC2) <- g$lc_PC2 == "Not significant"
  g$lc_PC2 <- droplevels(g$lc_PC2)
  if (tmap_ok) tm_shape(g) + tm_fill("lc_PC2", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 9
  else plot(g["lc_PC2"])
}
if (run) {
  lmc_PC <- local_multigeary(w, g[c("PC1","PC2")], significance_cutoff=0.00247,
    permutations=99999)
  g$lmc_PC <- factor(lisa_clusters(lmc_PC), levels=0:1,
    labels=lisa_labels(lmc_PC)[1:2])
  is.na(g$lmc_PC) <- g$lmc_PC == "Not significant"
  g$lmc_PC <- droplevels(g$lmc_PC)
  table(interaction((p.adjust(lisa_pvalues(lmc_PC), "fdr") < 0.01), g$lmc_PC))
}
if (run) {
  if (tmap_ok) tm_shape(g) + tm_fill("lmc_PC", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 10
  else plot(g["lmc_PC"])
}
if (run) {
  lmc_vars <- local_multigeary(w, st_drop_geometry(g)[, 1:6],
    significance_cutoff=0.00247, permutations=99999)
  g$lmc_vars <- factor(lisa_clusters(lmc_vars), levels=0:1,
    labels=lisa_labels(lmc_vars)[1:2])
  is.na(g$lmc_vars) <- g$lmc_vars == "Not significant"
  g$lmc_vars <- droplevels(g$lmc_vars)
  table(interaction((p.adjust(lisa_pvalues(lmc_vars), "fdr") < 0.01),
    g$lmc_vars))
}
if (run) {
  if (tmap_ok) tm_shape(g) + tm_fill("lmc_vars", textNA="Insignificant",
    colorNA="gray95") + tm_borders() # Fig. 11
  else plot(g["lmc_vars"])
}
```

**Comment by rsbivand** [comment] 2022-01-13 14:38
Yes, something odd in G_i. I didn't look at G*_i, but doubt that that is the reason, the localG_perm isn't well tested. I'm trying the multivariable case now, will add cases as I progress (if ...).

**Comment by rsbivand** [comment] 2022-01-13 15:50
This is Fig. 10, left **spdep**, right **rgeoda**:

![image](https://user-images.githubusercontent.com/10198404/149362771-e7525714-ba3c-416b-8215-4e238d1d75d9.png)

**Comment by rsbivand** [comment] 2022-01-13 15:56
and Fig. 11:

![image](https://user-images.githubusercontent.com/10198404/149363989-4139d946-5870-44ff-8bde-b508ea8dae34.png)

**Comment by rsbivand** [comment] 2022-01-13 15:58
I'll try to tidy up tomorrow my time and puch to the branch.

**Comment by JosiahParry** [comment] 2022-01-13 18:48
Looks good. Thank you for your assistance with this. Regarding the conditional permutation, I've put together an example below of calculating permutations of local C.

Rather than sampling the variable of interest which is incorrect as you pointed out, this randomizes the neighbors of i location (excluding $i$) so that j varied and i stays the same. `permute_listw()` returns a `listw` object which will work with localC (which provide the correct univariate and multivariate output as verified by rgeoda).

Below is an example of doing the conditional permutation calculation of Local C and comparisons of existing local C with rgeoda. What I do not understand is how to calculate the various p-values, unfortunately. 

I hope this may be of some help for the permutation case.

```

# Conditional Permutation of Neighbors ------------------------------------

g <- Guerry::gfrance85
nb <- spdep::poly2nb(g)
listw <- spdep::nb2listw(nb)

x <- g$Crime_pers

# function that shuffles nbs list elements
# ensures that $i$ is never within own list
# used as subroutine for permute_listw
shuffle_nbs <- function(i, n, card) {
  x <- 1:n
  sample(x[-i], size = card)
}

#' Conditionally permutes a listw object
permute_listw <- function(listw) {
  n <- length(listw$neighbours)
  
  cards <- spdep::card(listw$neighbours)
  # Shuffle the neighbors by randomly sampling from all possible neighbors 
  # except where x exists
  perm_nb <- mapply(shuffle_nbs, 1:n, n, cards) 
  class(perm_nb) <- c("nb", "list")
  listw$neighbours <- perm_nb
  
  listw
}

listw
plistw <- permute_listw(listw)

# Verify permuted listw doesn't contain i for any elements
i_in_j <- mapply(function(i, j) i %in% j, 
       1:length(plistw$neighbours), plistw$neighbours)

tinytest::expect_equal(i_in_j, rep(FALSE, length(plistw$neighbours)))


# Demonstrate computations w/ & w/out permutation
spdep::localC(x, listw)
spdep::localC(x, permute_listw(listw))

replicate(99, spdep::localC(x, permute_listw(listw)))


# Verify Local C with rgeoda ----------------------------------------------
g <- sf::st_as_sf(g)
queen_w <- rgeoda::queen_weights(g)

# test univariate computation
lg <- rgeoda::local_geary(queen_w, g[,"Crime_pers"])
splg <- spdep::localC(g$Crime_pers, listw)

tinytest::expect_equal(lg$lisa_vals, splg)

# test multivariate computation
lms <- rgeoda::local_multigeary(queen_w, g[,c("Crime_pers", "Wealth")], permutations = 999)

m <- sf::st_drop_geometry(g)[,c("Crime_pers", "Wealth")]
splc <- spdep::localC(m, listw)

tinytest::expect_equal(lms$lisa_vals, splc)



```

**Comment by rsbivand** [comment] 2022-01-15 13:47
Committed and pushed to multi_localC branch. You'll find the examples in `?localC`, but in time they perhaps should go into a vignette. There is a further puzzle (for all LISA) as to whether the significance cutoff is correct (GeoDa uses a folded two-sided p-value [0, 0.5] for LISA, so the p-values are not present in (0.5, 1]). col 5 are based on `punif()` rather than being folded, so `[,5] == [,6]*2`. This comes from work in progress on local Moran's I_i (code/data here: https://github.com/rsbivand/gaSI21 after chunk 60).

**Comment by JosiahParry** [comment] 2022-01-16 16:09
Reviewed this some this morning. It looks good. I'll review further tomorrow during holiday. 

I think having internal documentation for `permC_int()` would be helpful. 

Further, do you have any resources on "folded" p values that you can share? My searches have not been too successful.

**Comment by rsbivand** [comment] 2022-01-17 11:54
Tables 5-8 on p. 15-17 in this draft paper:
[GA_bivand_SI_2.pdf](https://github.com/r-spatial/spdep/files/7881585/GA_bivand_SI_2.pdf)
chunks 60-64 in script.

**Comment by JosiahParry** [comment] 2022-01-19 14:47
After further thinking, I believe your use of two-sided p-values from (0-1] is likely the correct approach here—though I'm no expert. Omission of half possible p-value seems questionable and overly generous. The inclusion of (0.5, 1] is much like a two-sided t-test providing a p-value that is twice the one-sided value.

**Comment by rsbivand** [comment] 2022-01-19 16:24
Thanks, not an expert either, but noticed discrepancies. In addition. GeoDa leaks a few values beyond 0.5, but that looks like a bug (I raise an issue there).

**Comment by rsbivand** [comment] 2022-01-19 16:24
Is it OK to merge the branch?

**Comment by JosiahParry** [comment] 2022-01-20 15:27
Yes. 
I confirmed that permC_int is conditional and that it provides the correct local C value for univariate and multivariate values. 
I went through the p-value computation and they seem correct as well.

**Comment by rsbivand** [comment] 2022-01-21 10:58
Branch merged.

**Closed by rsbivand** 2022-01-21 10:58 UTC
